package gensql

import (
	"testing"
)

const (
	pkg       = "mypkg"
	inputGlob = "some/files/*"
)

func TestBuildHeader(t *testing.T) {
	g := &Generator{pkg, inputGlob, ""}
	got := g.buildHeader()
	want := `// Do not edit this file directly!
// This code was automatically generated.
// Call "go generate" to regenerate it from latest source.

package mypkg
`
	gotWant(t, got, want)
}
